platform :ios, '9.0'

target 'TencentCloudUploaderExample' do
 use_modular_headers!
 pod 'TencentCloudUploader', :path => '../'

  target 'TencentCloudUploaderExampleTests' do
    inherit! :search_paths
  end
end
